In [42]:
import numpy as np

In [44]:
# define vectors
v1 = np.array([1,2,3])
v2 = np.array([-1,0,1])

# method 1
vm_1 = np.outer(v1,v2)

# method 2
# BAD
vm_2 = np.zeros((len(v1),len(v2)))
for i in range(0,len(v1)):
    for j in range(0,len(v2)):
        vm_2[i,j]=v1[i]*v2[j]

print(vm_1)
print('\n')
print(vm_2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


[[-1.  0.  1.]
 [-2.  0.  2.]
 [-3.  0.  3.]]
