In [7]:
import numpy as np

In [8]:
A = np.random.randn(13,2)
B = np.random.randn(13,2)

# note the different syntax compared to @ for matrix multiplication
C1 = np.multiply( A,B )
C2 = A*B

print(C1), print(' ')
print(C2), print(' ')

print(C1-C2)

[[-1.76024773e+00  2.36910762e-02]
 [-4.02061378e-01 -5.82081403e-02]
 [-2.09863712e-02 -3.15628311e+00]
 [-1.15063661e-02  1.12487904e+00]
 [-2.20571965e+00  1.59339454e-02]
 [-1.06886397e+00  2.06102509e+00]
 [-1.66474931e+00 -3.09777966e-01]
 [ 3.59593077e-04  1.07138791e+00]
 [ 1.43554174e-02 -2.33707145e-02]
 [ 1.89340592e-02 -1.18249768e-01]
 [ 6.24183241e-01  5.43406812e-01]
 [-2.49389505e-01  5.47575148e-01]
 [-3.42008615e-01  5.61090709e-02]]
 
[[-1.76024773e+00  2.36910762e-02]
 [-4.02061378e-01 -5.82081403e-02]
 [-2.09863712e-02 -3.15628311e+00]
 [-1.15063661e-02  1.12487904e+00]
 [-2.20571965e+00  1.59339454e-02]
 [-1.06886397e+00  2.06102509e+00]
 [-1.66474931e+00 -3.09777966e-01]
 [ 3.59593077e-04  1.07138791e+00]
 [ 1.43554174e-02 -2.33707145e-02]
 [ 1.89340592e-02 -1.18249768e-01]
 [ 6.24183241e-01  5.43406812e-01]
 [-2.49389505e-01  5.47575148e-01]
 [-3.42008615e-01  5.61090709e-02]]
 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0