In [38]:
import numpy as np

In [56]:
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row
print(A)

# vectors
r = [10,20,30,40]
c = [100,200,300]

# broadcast on the rows
print(A+r)

# broadcast on the columns
# print(A+c) # got error
print(A+np.reshape(c,(len(c),1)))

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
